#!/bin/bash
RED='\033[1;31m'
GREEN='\033[0;32m'
BLUE='\033[0;36m'
YELLOW='\033[1;33m'
ORANGE='\033[0;33m'
CYAN='\033[0;36m'

NC='\033[0m' # No Color

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
NEW_BRANCH=$1

echo ""
echo "git Command ----------> git branch -m  ${CURRENT_BRANCH} ${NEW_BRANCH}"
echo ""
if [ -n "$NEW_BRANCH"  ]; then
     git branch -m  ${CURRENT_BRANCH} ${NEW_BRANCH}
    echo ""
    echo -e "${GREEN}The branch renamed to $NEW_BRANCH${NC}"
    echo ""
else
    echo -e "${RED}!!!!!!!!!!!!!!!!!!! New Branch Name is empty !!!!!!!!!!!!!!!!!!!${NC}"
fi