#!/bin/bash
BLACK='\033[0;30m'        # Black
RED='\033[0;31m'          # Red
GREEN='\033[0;32m'        # Green
YELLOW='\033[0;33m'       # Yellow
BLUE='\033[0;34m'         # Blue
PURPLE='\033[0;35m'       # Purple
CYAN='\033[0;36m'         # Cyan
WHITE='\033[0;37m'        # White
BOLD='\033[1m'            # Bold Text
NC='\033[0m'              # No Color

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

MESSAGE=$1

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
BRANCH_NAME_ARRAY=(${BRANCH_NAME//-/ }) # BRANCH_NAME.split('-')
ARRAY_SIZE=${#BRANCH_NAME_ARRAY[@]}

if (( ARRAY_SIZE < 2 )) ; then
  echo "ERROR : branch name is not standard ------------ BRANCH = $BRANCH_NAME"
  exit
fi

if [ -z "$MESSAGE" ]; then # if MESSAGE is empty then
        for word in "${BRANCH_NAME_ARRAY[@]}"
        do
            if [ "$word" != "${BRANCH_NAME_ARRAY[0]}" ]; then # if word != branch_words[0] --> if i first 
                MESSAGE="$MESSAGE$word "
            fi
        done
fi

echo -e "commit message: ${BGreen}${MESSAGE}${NC}"

taskNumberMessage="#${BRANCH_NAME_ARRAY[0]} $MESSAGE"
echo ""
echo ""
echo -e "Branch -----------> ${PURPLE}$BRANCH_NAME${NC}"
echo ""
echo -e "Command ----------> ${PURPLE}git commit -am ${BGreen}\"$taskNumberMessage\"${NC}"
echo ""
#read  -n 1 -p "if every things is OK press [Enter] else any key... " key
echo ""
echo ""
if [ "$key" = "" ]; then
    git commit -am "$taskNumberMessage"
    echo ""
    echo "------------------------------------------"
    echo ""
else
    echo "________ Nothing happened! _______"
fi