#!/bin/bash
RED='\033[1;31m'
GREEN='\033[0;32m'
BLUE='\033[0;36m'
YELLOW="\033[33m"
ORANGE='\033[0;33m'
CYAN='\033[0;36m'
MAGENTA="\033[35m"


# Bright foreground colors
BRIGHT_BLACK="\033[90m"
BRIGHT_RED="\033[91m"
BRIGHT_GREEN="\033[92m"
BRIGHT_YELLOW="\033[93m"
BRIGHT_BLUE="\033[94m"
BRIGHT_MAGENTA="\033[95m"
BRIGHT_CYAN="\033[96m"
BRIGHT_WHITE="\033[97m"

# styles
# Text styles
B="\033[1m"
DIM="\033[2m"
I="\033[3m"
U="\033[4m"
BLINK="\033[5m"
REVERSE="\033[7m"
HIDDEN="\033[8m"
STRIKETHROUGH="\033[9m"
R='\e[0m' # Reser or Regular Text


INFO_COLOR=$CYAN

NC='\033[0m' # No Color

MAIN_CONTENT_TEMPLATE="
**⠀⠀⠀⠀⢀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⡀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠙⢷⣤⣤⣴⣶⣶⣦⣤⣤⡾⠋⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣼⣿⣿⣉⣹⣿⣿⣿⣿⣏⣉⣿⣿⣧⠀⠀⠀⠀
⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀
⣠⣄⠀⢠⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⡄⠀⣠⣄
⣿⣿⡇⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢸⣿⣿
⣿⣿⡇⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢸⣿⣿
⣿⣿⡇⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢸⣿⣿
⣿⣿⡇⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢸⣿⣿
⠻⠟⠁⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠈⠻⠟
⠀⠀⠀⠀⠉⠉⣿⣿⣿⡏⠉⠉⢹⣿⣿⣿⠉⠉⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⣿⣿⣿⡇⠀⠀⢸⣿⣿⣿⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⣿⣿⣿⡇⠀⠀⢸⣿⣿⣿⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠈⠉⠉⠀⠀⠀⠀⠉⠉⠁⠀**⠀⠀⠀



⠀

Hello everybody....

The latest version of the **Android trader application** can be downloaded from the following addresses:



**production_release_version: **   [**Release**](production_release_url)     [**Debug**](production_debug_url)    [Change Logs](production_change_log_url)

**staging_release_version: **    [**Release**](staging_release_url)      [**Debug**](staging_debug_url)    [Change Logs](staging_change_log_url)

**develop_release_version: **    [**Release**](develop_release_url)    [**Release**](develop_debug_url)   [Change Logs](develop_change_log_url)



@pakan @a.sedaghatipour @a.yaalimadad @m.mostafaei @sh.ranjbar
"

changeLog_production_url="https://azure.charisma.tech/Brokerage/Trader/_wiki/wikis/Trader.wiki/311/Production"
changeLog_staging_url="https://azure.charisma.tech/Brokerage/Trader/_wiki/wikis/Trader.wiki/315/Staging"
changeLog_develop_url="https://azure.charisma.tech/Brokerage/Trader/_wiki/wikis/Trader.wiki/312/Develop"

projectPath=/home/x/AndroidStudioProjects/AndriodTraderApp
apkRepositoryPath=/home/x/Downloads/Android-Apk

apkVersions=() # production (v1.0.10)
apk_azure_urls=()

find_string () {
  text=$1
  searchKey=$2
  echo ${text#*$searchKey}
}

find_position_string () {
  text=$1
  searchKey=$2
  substering_from_searchkey_to_end=${text#*$searchKey}
  echo $(( ${#text} - ${#substering_from_searchkey_to_end} - ${#searchKey} ))
}

sub_string () {
  text=$1
  firstKey=$2
  secondKey=$3
  firstPosition=$(find_position_string "$text" "$firstKey")
  secondPosition=$(find_position_string "$text" "$secondKey")
  sunstring=${text:$firstPosition:$secondPosition}
  echo $sunstring
}

press_any_key_to_continue(){
  read -p "-------------------- [Press enter to continue...] ------------------------"
}

print_line(){
  color=$1
  echo -e "${color}-----------------------------------------------------------${NC}"
}

get_app_version_name_with_path () {
  APP_VRESION_FILE=$1
  searchKey=$2

  flavorFile=`cat $APP_VRESION_FILE`
  find_result=${flavorFile#*"enum class TraderFlavor"} # result = ( val dimension: FlavorDimension, val applicationIdSuffix: String? = null,
  find_result=${flavorFile#*$searchKey} # result = applicationIdSuffix = ".develop", versionCode = 1, versionName = "1.0.29" ), stag ......
  position=$(( ${#flavorFile} - ${#find_result} - ${#searchKey} ))
  POTATION="\""

  find_result=${find_result#*"versionName"} # result = 1.0.29" ), staging ........
  find_result=${find_result#*$POTATION} # result = 1.0.29" ), staging ........

  next_potation=${find_result#*$POTATION}
  position_of_next_potation=$(( ${#find_result} - ${#next_potation} - ${#POTATION} ))

  version=${find_result:0:$position_of_next_potation}

  echo $version
}

get_above_version(){
  appversion_path_1=$1 # 1.0.33
  appversion_path_2=$2 # 1.0.34

  IFS='.'
  read -r -a splitted1 <<< $appversion_path_1
  read -r -a splitted2 <<< $appversion_path_2

  if (( splitted1[0] > splitted2[0] )); then
    echo "$appversion1"
    exit
  fi



  if (( splitted1[0] < splitted2[0] )); then
    echo "$appversion2"
    exit
  fi

  if (( splitted1[1] > splitted2[1] )); then
    echo "$appversion1"
    exit
  fi

  if (( splitted1[1] < splitted2[1] )); then
    echo "$appversion2"
    exit
  fi

  if (( splitted1[2] > splitted2[2] )); then
    echo "$appversion1"
    exit
  fi

  if (( splitted1[2] < splitted2[2] )); then
    echo "$appversion2"
    exit
  fi

  echo "$appversion1"
}

get_app_version_name (){
  APP_VRESION_FILE_1=/home/x/AndroidStudioProjects/AndriodTraderApp/build-logic/convention/src/main/kotlin/ir/charisma/android/trader/TraderFlavor.kt
  APP_VRESION_FILE_2=/home/x/AndroidStudioProjects/AndriodTraderApp_2/build-logic/convention/src/main/kotlin/ir/charisma/android/trader/TraderFlavor.kt
  searchKey=$1
  appversion1=$(get_app_version_name_with_path $APP_VRESION_FILE_1 $searchKey) # 1.0.33
  appversion2=$(get_app_version_name_with_path $APP_VRESION_FILE_2 $searchKey) # 1.0.34
  echo $(get_above_version $appversion1 $appversion2)
}

get_app_version_name_develop () {
  echo $(get_app_version_name 'develop(')
}

get_app_version_name_staging () {
  echo $(get_app_version_name 'staging(')
}

get_app_version_name_production () {
  echo $(get_app_version_name 'production(')
}

get_azure_url(){
  local environment=$1  # production | staging | develop
  local buildMode=$2    # debug | release
  local apkFileName=$3  # trader-production-debug-v1.0.55.apk
  echo "https://azure.charisma.tech/Brokerage/e45539a6-393c-4129-9db8-1ce5febabe6c/_apis/git/repositories/911efa6a-effe-4402-a7c3-dc86278891c0/items?path=/$environment/$buildMode/$apkFileName&versionDescriptor%5BversionOptions%5D=0&versionDescriptor%5BversionType%5D=0&versionDescriptor%5Bversion%5D=master&resolveLfs=true&%24format=octetStream&api-version=5.0&download=true"
}

is_exist_build_apk_in_local_storage() {
  local environment=$1 #"production"
  local buildMode=$2 #"debug"
  local apkFileName="app-$environment-$buildMode.apk"
  local apkProjectPath="$projectPath/app/$environment/$buildMode/$apkFileName"

  if [ -f $apkProjectPath ]; then
    echo "true"
  else
    echo "false"
  fi
}

move_apk_to_repository() {
  appVersion=$1 #"1.0.29"
  local environment=$2 #"production"
  local buildMode=$3 #"debug"
  local apkFileName="app-$environment-$buildMode.apk"
  local willChangeAPKFileName="trader-$environment-$buildMode-v$appVersion.apk"
  local apkProjectPath="$projectPath/app/$environment/$buildMode/$apkFileName"
  local willChangeAPKPath="$apkRepositoryPath/$environment/$buildMode/$willChangeAPKFileName"

  if [  -f "$willChangeAPKPath" ]; then
    echo -e  "${ORANGE}Already File exits in APK repository : $willChangeAPKPath${NC}"
    apk_azure_urls+=("$(get_azure_url "$environment" "$buildMode" "$willChangeAPKPath")")
    return
  fi


  if [  -f "$apkProjectPath" ]; then
    echo "Renaming apk from  [$apkFileName]  -->  [$willChangeAPKFileName] "
    read -p "Press enter to continue..."
    mv "$apkProjectPath" "$willChangeAPKPath"
    echo -e "${GREEN}Moved apk from:  $apkProjectPath${NC}"
    echo -e "${GREEN}Moved apk to  :  $willChangeAPKPath${NC}"
    apkVersions+=("$environment (v$appVersion)") # production (v1.0.10)
    apk_azure_urls+=("$(get_azure_url "$environment" "$buildMode" "$willChangeAPKFileName")")
  else
    echo -e  "${BRIGHT_BLACK}File not exist! --> $apkProjectPath${NC}"
  fi
}

move_apk_to_repository_develop() {
  appVersion=$(get_app_version_name_develop)
  move_apk_to_repository "$appVersion" "develop" "debug"
  move_apk_to_repository "$appVersion" "develop" "release"
}

move_apk_to_repository_staging() {
  appVersion=$(get_app_version_name_staging)
  move_apk_to_repository "$appVersion" "staging" "debug"
  move_apk_to_repository "$appVersion" "staging" "release"
}

move_apk_to_repository_production() {
  appVersion=$(get_app_version_name_peoduction)
  move_apk_to_repository "$appVersion" "production" "debug"
  move_apk_to_repository "$appVersion" "production" "release"
}


move_all_apk_to_repository() {
  move_apk_to_repository_develop
  move_apk_to_repository_staging
  move_apk_to_repository_production
}

print_apk_local_version_if_exist() {
  local environment=$1
  local version=$2
  local textColor=$BRIGHT_BLACK
  local buildTypeText=" "
  if [[ $(is_exist_build_apk_in_local_storage "$environment" release) == "true" ]]; then :
    textColor=$GREEN
    buildTypeText+="   ${GREEN}${B}release${R}${NC}"
  fi

  if [[ $(is_exist_build_apk_in_local_storage "$environment" debug) == "true" ]]; then :
    textColor=$GREEN
    buildTypeText+="   ${ORANGE}${B}debug${R}${NC}"
  fi


  echo -e "          ${textColor}${B}$environment v${version}${R} ${buildTypeText} ${R} ${NC}"

}

print_is_correct_app_version_name() {

  print_apk_local_version_if_exist "production" "$(get_app_version_name_peoduction)"
  print_apk_local_version_if_exist "staging" "$(get_app_version_name_staging)"
  print_apk_local_version_if_exist "develop" "$(get_app_version_name_develop)"

  press_any_key_to_continue
}

commit_and_push_apks(){
  # remove duplicate elements in $apkVersions array
  declare -A apkVersions_removeDuplicates
  for i in "${apkVersions[@]}"; do apkVersions_removeDuplicates["$i"]=1; done

  commitMessage="Added APKs "


  i=0
  for apkEnvVersion in "${!apkVersions_removeDuplicates[@]}"; do
    if [[ $i -eq 0 ]]; then
      commitMessage+="$apkEnvVersion"
    else
      commitMessage+=" and $apkEnvVersion"
    fi
    ((i++))
  done

  cd "$apkRepositoryPath"
  git add .
  git status
  echo -e "Command ----> git commit -am \"$commitMessage\""
  press_any_key_to_continue
  gitcommit "\"$commitMessage\""
  gitpush_origin_current_branch
}

fetch_and_switch_repository_branch() {
  branch=$1
  if [[ -n "$branch" ]]
  then
    cd "$apkRepositoryPath"
    git pull origin "\"$branch\""
    echo "1" # not empty
  else
    echo "0" # empty
  fi
}

isExistString(){
  local mainString=$1
  local substring=$2
  if echo "$mainString" | grep -q "$substring"; then
    echo "true";
  else
    echo "false";
  fi
}

isExistApkPathInAzureUrlArray(){
  local environment=$1 # production/staging/develop
  local buildType=$2 # example (one of):  dubeug / release=$1 # production/staging/develop @@@@@@
  for apkUrl in "${apk_azure_urls[@]}"; do # apkUrl = https://azure.charisma.tech/Brokere....
    if($(isExistString $apkUrl $environment) = "true") then
      if($(isExistString $apkUrl $buildType) = "true") then
        echo "true"
        return
      fi
    fi
  done
  echo "false"
}


get_apk_url(){ # output : https://azure.charisma.tech/Brokerage/e4553....
  env=$1 # example (one of) : develop / staging / production
  buildType=$2 # example (one of):  dubeug / release
  for apkUrl in "${apk_azure_urls[@]}"; do # apkUrl = https://azure.charisma.tech/Brokere....
    if($(isExistString $apkUrl $env) = "true") then
      if($(isExistString $apkUrl $buildType) =  "true") then
        echo -e "${BLUE}$apkUrl${NC}"
        return
      fi
    fi
  done
}

get_apk_urls_of_production(){
  if($(isExistApkPathInAzureUrlArray production release) = "true") then
    echo "Production v$(get_app_version_name_peoduction)"
    get_apk_url production release
  fi
}

print_apk_urls_of_staging(){
  if($(isExistApkPathInAzureUrlArray staging release) = "true") then
    echo "Staging v$(get_app_version_name_staging)"
    get_apk_url staging release

  fi
}

print_apk_urls_of_develop(){
  if($(isExistApkPathInAzureUrlArray develop release) = "true") then
    echo "Develop v$(get_app_version_name_develop)"
    get_apk_url develop release
  fi
}

print_develop_changes_url_if_needs(){
  if($(isExistApkPathInAzureUrlArray develop) = "true") then
    echo "Develop: https://azure.charisma.tech/Brokerage/Trader/_wiki/wikis/Trader.wiki/312/Develop"
  fi
}

print_staging_changes_url_if_needs(){
  if($(isExistApkPathInAzureUrlArray staging) = "true") then
    echo "Staging: https://azure.charisma.tech/Brokerage/Trader/_wiki/wikis/Trader.wiki/315/Staging"
  fi
}

print_production_changes_url_if_needs(){
  if($(isExistApkPathInAzureUrlArray production) = "true") then
    echo "Production: https://azure.charisma.tech/Brokerage/Trader/_wiki/wikis/Trader.wiki/311/Production"
  fi
}

delete_line_if_contain_string(){
  local mainString=$1
  local targetString=$2


#  local text="$1"
#  local pattern="$2"
  # Use grep -v to omit lines containing the pattern
  printf "%s" "$mainString" | grep -v -- "$targetString"

#  rt=$("$mainString" | sed "/$targetString/d")
#  echo $rt
}

get_key_change_log_text() {
  environment=$1
  if [[ $environment == "production" ]]; then :
    echo "production_change_log_text"
  elif [[ $environment == "staging" ]]; then :
    echo "staging_change_log_text"
  else
    echo "develop_change_log_text"
  fi
}

get_key_change_log_url() {
  environment=$1
  if [[ $environment == "production" ]]; then :
    echo "production_change_log_url"
  elif [[ $environment == "staging" ]]; then :
    echo "staging_change_log_url"
  else
    echo "develop_change_log_url"
  fi
}



get_change_log_text() {
  environment=$1
  if [[ $environment == "production" ]]; then :
    echo "Production"
  elif [[ $environment == "staging" ]]; then :
    echo "Staging"
  else
    echo "Develop"
  fi
}

get_change_log_url() {
  environment=$1
  if [[ $environment == "production" ]]; then :
    echo "$changeLog_production_url"
  elif [[ $environment == "staging" ]]; then :
    echo "$changeLog_staging_url"
  else
    echo "$changeLog_develop_url"
  fi
}

get_release_description_and_url_if_exist(){

  local description="$1"
  local environment="$2"
  local builtType="$3"
  local versionName="$4"
  local key_version="$5"
  local key_url="$6"

  local url


  local key_change_log_text=$(get_key_change_log_text "$environment")
  local key_change_log_url=$(get_key_change_log_url "$environment")

  local change_log_text=$(get_change_log_text "$environment")
  local change_log_url=$(get_change_log_url "$environment")


  if [[ $(isExistApkPathInAzureUrlArray "$environment" "$builtType") == "true" ]]; then :

    url=$(get_apk_url "$environment" "$builtType")

    description="${description/$key_version/$versionName}"
    description="${description/$key_url/$url}"
    description="${description/$key_change_log_text/$change_log_text}"
    description="${description/$key_change_log_url/$change_log_url}"

#  else
#    description=$(delete_line_if_contain_string "$description" "$key_version")
#    description=$(delete_line_if_contain_string "$description" "$key_url")
#    description=$(delete_line_if_contain_string "$description" "$key_change_log_text")
#    description=$(delete_line_if_contain_string "$description" "$key_change_log_url")
  fi
  echo "$description"
}

print_release_description(){

  local description="$MAIN_CONTENT_TEMPLATE"

  description=$(get_release_description_and_url_if_exist "$description" "production" "release" "Production v$(get_app_version_name_peoduction)" "production_release_version" "production_release_url")
  description=$(get_release_description_and_url_if_exist "$description" "production" "debug" "Production v$(get_app_version_name_peoduction) (Debug)" "production_debug_version" "production_debug_url")

  description=$(get_release_description_and_url_if_exist "$description" "staging" "release" "Staging v$(get_app_version_name_staging)" "staging_release_version" "staging_release_url")
  description=$(get_release_description_and_url_if_exist "$description" "staging" "debug" "Staging v$(get_app_version_name_staging) (Debug)" "staging_debug_version" "staging_debug_url")

  description=$(get_release_description_and_url_if_exist "$description" "develop" "release" "Develop v$(get_app_version_name_develop)" "develop_release_version" "develop_release_url")
  description=$(get_release_description_and_url_if_exist "$description" "develop" "debug" "Develop v$(get_app_version_name_develop) (Debug)" "develop_debug_version" "develop_debug_url")


  echo -e "$description"

}

print_all_exist_apk_version_name_and_wait_to_press_any_key(){
  print_line $INFO_COLOR
  echo -e "${INFO_COLOR}Step 1: Is correct the app versions?${NC}"
  print_line $INFO_COLOR

  print_is_correct_app_version_name
}

moving_all_exit_apk_to_git_repository(){
  print_line $INFO_COLOR
  echo -e "${INFO_COLOR}Step 2: Moving all exit apk to git repository${NC}"
  print_line $INFO_COLOR
  move_all_apk_to_repository
}

commit_and_push_apks_with_print_infos(){
  print_line $INFO_COLOR
  echo -e "${INFO_COLOR}Step 3: Commit and push APKs${NC}"
  print_line $INFO_COLOR


  #commit_and_push_apks
}
#############################################################################
#############################################################################
# BASH STARTED
#############################################################################
#############################################################################

print_all_exist_apk_version_name_and_wait_to_press_any_key
moving_all_exit_apk_to_git_repository
commit_and_push_apks_with_print_infos
print_release_description

